In [23]:
import pandas as pd
import numpy as np

rs = 42

In [24]:
df = pd.read_csv('large.csv')
df = df.sample(frac=1, random_state = rs)
df

,LATITUDE,LONGITUDE,AGE,YEARS_WITH_COMPANY,ANNUAL_KILOMETERS,DAILY_KILOMETERS,YEARS_LICENSED,VEHICLE_YEAR,NUMBER_OF_DRIVERS,NUMBER_OF_VEHICLES,...,INCURRED_LOSS_DCPD,GENDER,DRIVER_MARTIAL_STATUS,DRIVER_TRAINING_IND,VEHICLE_AGE,YEARS_SINCE_AT_FAULT_CLAIM,YEARS_SINCE_NOT_AT_FAULT_CLAIM,YEARS_SINCE_MINOR_CONVICTION,YEARS_SINCE_MAJOR_CONVICTION,YEARS_SINCE_SERIOUS_CONVICTION
104241,46.022276,-84.347301,54.0,6.0,NaN,9.0,33.0,1999.0,NaN,2.0,...,0,F,S,N,17.0,3.0,2.0,NaN,NaN,NaN
199676,44.136240,-80.274226,55.0,5.0,15000.0,9.0,33.0,2007.0,1.0,NaN,...,0,F,M,N,9.0,NaN,NaN,NaN,NaN,NaN
140199,44.937096,-76.966918,60.0,5.0,11000.0,3.0,38.0,2004.0,2.0,2.0,...,0,F,M,N,11.0,NaN,NaN,NaN,NaN,NaN
132814,42.722584,-80.188429,47.0,1.0,11000.0,7.0,25.0,2007.0,1.0,1.0,...,0,M,S,N,11.0,1.0,3.0,NaN,NaN,NaN
408697,42.999289,-81.477359,40.0,7.0,14000.0,8.0,21.0,2007.0,1.0,2.0,...,0,M,M,N,7.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259178,48.085291,-82.027790,51.0,8.0,13000.0,5.0,29.0,2004.0,1.0,2.0,...,0,M,S,N,8.0,NaN,NaN,NaN,NaN,NaN
365838,48.664742,-86.990759,46.0,8.0,11000.0,6.0,25.0,2006.0,1.0,1.0,...,17134,F,S,N,10.0,NaN,NaN,NaN,NaN,NaN
131932,49.081518,-89.582400,49.0,8.0,13000.0,4.0,26.0,2006.0,NaN,1.0,...,0,F,S,N,6.0,NaN,NaN,NaN,NaN,NaN
146867,44.973110,-81.612594,45.0,5.0,16000.0,6.0,26.0,2004.0,1.0,1.0,...,0,M,S,N,12.0,NaN,NaN,NaN,NaN,NaN
121958,47.489187,-79.318710,46.0,6.0,10000.0,3.0,21.0,2004.0,1.0,2.0,...,0,F,M,N,11.0,NaN,5.0,NaN,NaN,NaN

In [25]:
df = df[df['INCURRED_LOSS_DCPD'] > 0]
df = df.drop(['INCURRED_LOSS_COLLISION','INCURRED_LOSS_COMPREHENSIVE'], axis=1)
df

,LATITUDE,LONGITUDE,AGE,YEARS_WITH_COMPANY,ANNUAL_KILOMETERS,DAILY_KILOMETERS,YEARS_LICENSED,VEHICLE_YEAR,NUMBER_OF_DRIVERS,NUMBER_OF_VEHICLES,...,INCURRED_LOSS_DCPD,GENDER,DRIVER_MARTIAL_STATUS,DRIVER_TRAINING_IND,VEHICLE_AGE,YEARS_SINCE_AT_FAULT_CLAIM,YEARS_SINCE_NOT_AT_FAULT_CLAIM,YEARS_SINCE_MINOR_CONVICTION,YEARS_SINCE_MAJOR_CONVICTION,YEARS_SINCE_SERIOUS_CONVICTION
158067,46.492018,-77.383547,25.0,1.0,14000.0,13.0,5.0,2008.0,1.0,1.0,...,18145,M,S,N,NaN,NaN,3.0,NaN,NaN,NaN
226642,45.929424,-81.698666,51.0,6.0,10000.0,2.0,28.0,2004.0,1.0,NaN,...,9693,F,M,N,10.0,NaN,NaN,NaN,NaN,NaN
340119,43.750325,-77.438572,57.0,0.0,12000.0,8.0,29.0,2006.0,3.0,2.0,...,19504,M,M,N,12.0,3.0,0.0,NaN,NaN,NaN
232595,46.140898,-79.830084,62.0,7.0,11000.0,4.0,38.0,2004.0,1.0,2.0,...,17161,M,S,N,8.0,NaN,NaN,NaN,NaN,NaN
59416,47.035907,NaN,49.0,9.0,12000.0,3.0,31.0,2005.0,2.0,2.0,...,18212,F,M,N,7.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31551,47.074756,-80.727498,47.0,8.0,11000.0,7.0,26.0,2004.0,2.0,2.0,...,16681,F,M,N,15.0,NaN,NaN,NaN,NaN,NaN
156730,43.123836,-78.816298,46.0,4.0,14000.0,6.0,23.0,2005.0,1.0,1.0,...,16473,F,S,N,10.0,NaN,1.0,NaN,NaN,NaN
214176,49.458087,-82.387098,51.0,10.0,9000.0,5.0,30.0,2006.0,2.0,2.0,...,17737,F,M,N,8.0,NaN,4.0,NaN,NaN,NaN
207892,45.185783,-77.180127,53.0,7.0,12000.0,8.0,35.0,2005.0,NaN,NaN,...,18464,F,M,N,10.0,NaN,4.0,NaN,NaN,NaN
365838,48.664742,-86.990759,46.0,8.0,11000.0,6.0,25.0,2006.0,1.0,1.0,...,17134,F,S,N,10.0,NaN,NaN,NaN,NaN,NaN

In [26]:
df.GENDER = df.GENDER.apply(lambda x: 1 if x == 'M' else 0)
df.DRIVER_MARTIAL_STATUS = df.DRIVER_MARTIAL_STATUS.apply(lambda x: 1 if x == 'S' else 0)
df.DRIVER_TRAINING_IND = df.DRIVER_TRAINING_IND.apply(lambda x: 1 if x == 'Y' else 0)
df.VEHICLE_AGE = df.VEHICLE_AGE.apply(lambda x: max(x,0))
df

,LATITUDE,LONGITUDE,AGE,YEARS_WITH_COMPANY,ANNUAL_KILOMETERS,DAILY_KILOMETERS,YEARS_LICENSED,VEHICLE_YEAR,NUMBER_OF_DRIVERS,NUMBER_OF_VEHICLES,...,INCURRED_LOSS_DCPD,GENDER,DRIVER_MARTIAL_STATUS,DRIVER_TRAINING_IND,VEHICLE_AGE,YEARS_SINCE_AT_FAULT_CLAIM,YEARS_SINCE_NOT_AT_FAULT_CLAIM,YEARS_SINCE_MINOR_CONVICTION,YEARS_SINCE_MAJOR_CONVICTION,YEARS_SINCE_SERIOUS_CONVICTION
158067,46.492018,-77.383547,25.0,1.0,14000.0,13.0,5.0,2008.0,1.0,1.0,...,18145,1,1,0,NaN,NaN,3.0,NaN,NaN,NaN
226642,45.929424,-81.698666,51.0,6.0,10000.0,2.0,28.0,2004.0,1.0,NaN,...,9693,0,0,0,10.0,NaN,NaN,NaN,NaN,NaN
340119,43.750325,-77.438572,57.0,0.0,12000.0,8.0,29.0,2006.0,3.0,2.0,...,19504,1,0,0,12.0,3.0,0.0,NaN,NaN,NaN
232595,46.140898,-79.830084,62.0,7.0,11000.0,4.0,38.0,2004.0,1.0,2.0,...,17161,1,1,0,8.0,NaN,NaN,NaN,NaN,NaN
59416,47.035907,NaN,49.0,9.0,12000.0,3.0,31.0,2005.0,2.0,2.0,...,18212,0,0,0,7.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31551,47.074756,-80.727498,47.0,8.0,11000.0,7.0,26.0,2004.0,2.0,2.0,...,16681,0,0,0,15.0,NaN,NaN,NaN,NaN,NaN
156730,43.123836,-78.816298,46.0,4.0,14000.0,6.0,23.0,2005.0,1.0,1.0,...,16473,0,1,0,10.0,NaN,1.0,NaN,NaN,NaN
214176,49.458087,-82.387098,51.0,10.0,9000.0,5.0,30.0,2006.0,2.0,2.0,...,17737,0,0,0,8.0,NaN,4.0,NaN,NaN,NaN
207892,45.185783,-77.180127,53.0,7.0,12000.0,8.0,35.0,2005.0,NaN,NaN,...,18464,0,0,0,10.0,NaN,4.0,NaN,NaN,NaN
365838,48.664742,-86.990759,46.0,8.0,11000.0,6.0,25.0,2006.0,1.0,1.0,...,17134,0,1,0,10.0,NaN,NaN,NaN,NaN,NaN

In [27]:
y = df['INCURRED_LOSS_DCPD']
X = df.drop(labels='INCURRED_LOSS_DCPD',axis=1)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = rs)

X_val, X_test, y_val, y_test = train_test_split(X_test,y_test, test_size=0.5, random_state = rs)

In [29]:
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV

params = {
        'max_depth': [2, 3, 5, 7, 9, 11],
        'n_estimators': [1000],
        'colsample_bytree': [0.6, 0.8, 1], 
        'subsample': [0.6, 0.8, 1], 
        'learning_rate': [0.01, 0.05, 0.1, 0.2, 0.3], 
        'random_state': [rs]
    }

xgb = GridSearchCV(XGBRegressor(), cv=5, param_grid=params, verbose=2, n_jobs=-1)


xgb.fit(
    X_train, 
    y_train, 
    eval_metric="rmse", 
    eval_set=[(X_train, y_train), (X_val, y_val)], 
    verbose=True, 
    early_stopping_rounds = 10)

Fitting 5 folds for each of 270 candidates, totalling 1350 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.

KeyboardInterrupt:

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt

y_pred = xgb.best_estimator_.predict(X_test)

rmse = sqrt(mean_squared_error(y_pred,y_test))

rmse

In [ ]:
from pickle import dump

with open('xgb.pkl','wb') as f:
    dump(xgb.best_estimator_,f)